[project]
name = "spark-hh015"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "FumiHubCNS", email = "fendo@cns.s.u-tokyo.ac.jp" }
]
requires-python = ">=3.13"
dependencies = [
  "pyspark==4.0.1",
  "pandas",
  "pyarrow",
  "numpy",
  "matplotlib",
  "plotly",
  "scipy",
  "marimo>=0.19.9",
  "ipython>=9.10.0",
  "ipywidgets>=8.1.8",
  "marimo-lib",
  "samidare-lib",
  "spark-oedo",
  "anywidget>=0.9.21",
]

[tool.uv.sources]
samidare-lib = { git = "https://github.com/FumiHubCNS/samidare-lib"} 
marimo-lib = { git = "https://github.com/FumiHubCNS/marimo-lib"} 
spark-oedo = { git = "https://github.com/FumiHubCNS/spark-oedo.git" , rev = "uv-package" }

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"


